### ISSUE TITLE
Grade doesn't save in student group.

### ISSUE THREAD

**Issue by Lama64** [PSE-Timetable/uftos#288]
The id of the student group is present in the student group until the repository save function is called, after which the grade is nowhere to be found in the object returned by the save function and is also not present in the student group returned by `getById()`.

**Comment by marcelfloe** [comment]
Same issue as in #242

**Comment by Lama64** [comment]
The map of the student group request dto maps to new entities which only contain the id. Therepository save function doesn't save these newly created entities correctly, resulting in the grades never being saved.
